version: '3'
services:
  oracle-db:
    build: .
    ports:
      - '1521:1521'
    environment:
      - ORACLE_PWD=oracle123
    volumes:
      - oracle-data:/opt/oracle/oradata
    healthcheck:
      test:
        [
          'CMD',
          'sqlplus',
          '-L',
          'sys/oracle123@//localhost:1521/XE as sysdba',
          '@/opt/oracle/scripts/startup/healthcheck.sql',
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
